[tool.poetry]
name = "pdl-api"
version = "0.1.0"
description = ""
authors = ["Yong Wook Kim <ywkim@illinois.edu>"]
readme = "README.md"
packages = [{include = "pdl_api"}]

[tool.poetry.dependencies]
python = ">=3.8"
flask = ">=1.1.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
