openapi: 3.0.0
info:
  title: Policy Design Lab API
  description: Policy Design Lab API Documentation
  version: 0.1.0
servers:
- url: https://localhost
  description: Production server
- url: https://localhost
  description: Test server
- url: https://localhost
  description: Development server
tags:
- name: Pdl API
  description: API endpoints for managing pdl object.
paths:
  /pdl:
    get:
      tags:
        - Pdl
      summary: Get the list of program records
      description: |
        By passing in the appropriate options, you can search for program records matching your criteria in the system
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Program-record'
        400:
          description: Bad request
        401:
          description: Unauthorized
        500:
          description: Internal error
  /pdl/summary:
    get:
      tags:
        - Summary
      summary: Get the list of summary records
      description: |
        By passing in the appropriate options, you can search for summary records matching your criteria in the system
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Summary'
        400:
          description: Bad request
        401:
          description: Unauthorized
        500:
          description: Internal error
  /pdl/program-record:
    get:
      tags:
        - Pdl
      summary: Get the list of program records
      description: |
        By passing in the appropriate options, you can search for program records matching your criteria in the system
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Program-record'
        400:
          description: Bad request
        401:
          description: Unauthorized
        500:
          description: Internal error
  /pdl/program-record/{program_record_id}:
    get:
      tags:
      - Pdl
      summary: Find program record by ID
      description: |
        Returns a single profile by program records id
      parameters:
      - name: program_record_id
        in: path
        description: ID of program record to return
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Program-record'
            application/xml:
              schema:
                $ref: '#/components/schemas/Program-record'
        400:
          description: Invalid ID supplied
        401:
          description: Unauthorized
        404:
          description: Profile not found
        500:
          description: Internal error
components:
  schemas:
    Summary:
      type: object
      nullable: true
      properties:
        title:
          type: string
        state:
          nullable: true
          type: string
        fiscal_year:
          nullable: true
          type: integer
        amount:
          nullable: true
          type: string
    Program-record:
      type: object
      nullable: true
      properties:
        program_record_id:
          type: integer
        pay_year:
          nullable: true
          type: string
        program_id:
          nullable: true
          type: integer
        payment:
          nullable: true
          type: number
        practice_code:
          nullable: true
          type: integer
        state_code:
          nullable: true
          type: integer
        category1_code:
          nullable: true
          type: integer
        category2_code:
          nullable: true
          type: integer
