openapi: 3.0.0
info:
  title: Policy Design Lab API
  description: Policy Design Lab API Documentation
  version: 0.1.0
servers:
- url: https://localhost
  description: Production server
- url: https://localhost
  description: Test server
- url: https://localhost
  description: Development server
tags:
- name: Pdl API
  description: API endpoints for managing pdl object.
paths:
  /pdl/summary:
    get:
      tags:
        - Summary
      summary: Get the list of summary records
      description: |
        By passing in the appropriate options, you can search for summary records matching your criteria in the system
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Summary'
        400:
          description: Bad request
        401:
          description: Unauthorized
        500:
          description: Internal error
  /pdl/states:
    get:
      tags:
        - States
      summary: Get the list of state records
      description: |
        By passing in the appropriate options, you can search for state records matching your criteria in the system
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/State'
        400:
          description: Bad request
        401:
          description: Unauthorized
        500:
          description: Internal error
  /pdl/allprograms:
    get:
      tags:
        - All Programs
      summary: Get the list of all program records
      description: |
        By passing in the appropriate options, you can search for all program records matching your criteria in the system
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AllPrograms'
        400:
          description: Bad request
        401:
          description: Unauthorized
        500:
          description: Internal error
components:
  schemas:
    Summary:
      type: object
      nullable: true
      properties:
        title:
          type: string
        state:
          nullable: true
          type: string
        fiscal_year:
          nullable: true
          type: integer
        amount:
          nullable: true
          type: string
    State:
      type: object
      nullable: true
      properties:
        id:
          type: string
        val:
          nullable: true
          type: string
    AllPrograms:
      type: object
      nullable: true
      properties:
        state:
          type: string
        crop_ins_2018:
          nullable: true
          type: number
        crop_ins_2019:
          nullable: true
          type: number
        crop_ins_2020:
          nullable: true
          type: number
        crop_ins_2021:
          nullable: true
          type: number
        crop_ins_2022:
          nullable: true
          type: number
        crop_ins_total:
          nullable: true
          type: number
        snap_2018:
          nullable: true
          type: number
        snap_2019:
          nullable: true
          type: number
        snap_2020:
          nullable: true
          type: number
        snap_2021:
          nullable: true
          type: number
        snap_2022:
          nullable: true
          type: number
        snap_total:
          nullable: true
          type: number
        title_1_2018:
          nullable: true
          type: number
        title_1_2019:
          nullable: true
          type: number
        title_1_2020:
          nullable: true
          type: number
        title_1_2021:
          nullable: true
          type: number
        title_1_202:
          nullable: true
          type: number
        title_1_total:
          nullable: true
          type: number
        title_2_2018:
          nullable: true
          type: number
        title_2_2019:
          nullable: true
          type: number
        title_2_2020:
          nullable: true
          type: number
        title_2_2021:
          nullable: true
          type: number
        title_2_202:
          nullable: true
          type: number
        title_2_total:
          nullable: true
          type: number
        prog.all_programs_total_2018:
          nullable: true
          type: number
        prog.all_programs_total_2019:
          nullable: true
          type: number
        prog.all_programs_total_2020:
          nullable: true
          type: number
        prog.all_programs_total_2021:
          nullable: true
          type: number
        prog.all_programs_total_2022:
          nullable: true
          type: number
        all_programs_total_18_22:
          nullable: true
          type: number
